### PR TITLE
Fix vote controls

### LINKED ISSUE #75: Slider has to become smaller
Bildschirmfoto 2019-09-05 um 23 08 35

### LINKED ISSUE #112: changing UI of voting screen before voting and after voting
## desired UI:
**before any vote was casted on this issue** : 
- no withdrawal button
- changing name of `send vote` to `VOTE SENDEN`
- chaning yes / no to `JA` and `NEIN`

image

**after a vote was casted already**
- adding withdrawal button with the name: `ZURÜCKSETZEN`
- changing name of `VOTE SENDEN` to `VOTE ÄNDERN`

image

### PR DESCRIPTION
**Pull request by vrde**
Fix #75, Fix #112 

# Before voting
image

# After voting
image

### CODE REVIEW

File: src/volt/components/VoteControls/index.js [hunk 1]
```diff
@@ -715,27 +715,27 @@ class VoteControls extends Component {
...
-          alreadyVoted={alreadyVoted}
-        />
-        <ActionButton disabled={voteDisabled} onClick={this.submitOrUpdateVote}>
-          { alreadyVoted ? 'Update Vote' : 'Send Vote' }
-        </ActionButton>
-        <ActionButton onClick={this.withdrawVote}>Withdraw</ActionButton>
+
+        <SubContainer>
+          <StyledSlider
+      mb={4}
```
Comment (MaxStalker) [inline src/volt/components/VoteControls/index.js]: Some spacing issue here? :)

File: src/volt/components/VoteControls/styles.js [hunk 2]
```diff
@@ -30,6 +25,7 @@ export const StyledSlider = styled(Slider).attrs(() => ({}))`
   user-select: none;
   width: 100%;
   min-width: auto;
+  margin-bottom: 8px;
```
Comment (MaxStalker) [inline src/volt/components/VoteControls/styles.js]: Maybe bettrer to put inside of attributes `mb:  2`

**Review by MaxStalker — CHANGES_REQUESTED** [review]

File: src/volt/components/VoteControls/styles.js (hunk 2 above)
Comment (vrde) [reply src/volt/components/VoteControls/styles.js]: I tried but it doesn't pick it up... any ideas?

Comment (MaxStalker) [reply src/volt/components/VoteControls/styles.js]: Did you keep this one here? :)
need to remove it as well. otherwise what you specify in attrs will be overwritten

Comment (vrde) [reply src/volt/components/VoteControls/styles.js]: image

:woman_shrugging:

Comment (MaxStalker) [reply src/volt/components/VoteControls/styles.js]: Right... Screw it then, keep as margin-bottom then.
Just add 
`margin-bottom: ${({theme}) => `${theme.space[2]}px`};`

**Review by MaxStalker — APPROVED** [review]
