### PR TITLE
fix: make Burn PK button work

### LINKED ISSUE #53: burn button doesn't work
click -> no effect

### PR DESCRIPTION
**Pull request by troggy**
Resolves #53 #66

### CODE REVIEW

File: src/volt/components/VoteControls/styles.js [hunk 1]
```diff
@@ -77,3 +77,15 @@ export const ActionButton = styled.button.attrs(() => ({}))`
...
 `;
+
+export const PrimaryButton = styled(ActionButton)`
+  margin-bottom: 0;
+  background-color: ${({ theme }) => theme.colors.voltBrandMain}
+`;
+
+export const OutlineButton = styled(ActionButton)`
+  margin-bottom: 0;
+  border-color: ${({ theme }) => theme.colors.voltBrandMain}
```
Comment (MaxStalker) [inline src/volt/components/VoteControls/styles.js]: Can you add semicolons in on lines 88-90?

File: src/volt/components/VoteControls/styles.js [hunk 2]
```diff
@@ -77,3 +77,15 @@ export const ActionButton = styled.button.attrs(() => ({}))`
     opacity: 0.3;
   }
 `;
+
+export const PrimaryButton = styled(ActionButton)`
+  margin-bottom: 0;
+  background-color: ${({ theme }) => theme.colors.voltBrandMain}
```
Comment (MaxStalker) [inline src/volt/components/VoteControls/styles.js]: Semicolon missing

**Review by MaxStalker — CHANGES_REQUESTED** [review]

**Review by MaxStalker — APPROVED** [review]
