### PR TITLE
Fix broken voting

### LINKED ISSUE #32: Casting vote and withdrawal is broken after master was merged into branch

### PR DESCRIPTION
**Pull request by MaxStalker**
Resolves #32

### CODE REVIEW

File: src/volt/components/VoteControls/index.js [hunk 1]
```diff
@@ -92,50 +92,19 @@ class VoteControls extends Component {
...
-    finalBytecode = replaceAll(
-      finalBytecode,
-      BALANCE_CARD,
-      CONTRACT_VOICE_BALANCE_CARD
-    );
-    finalBytecode = replaceAll(finalBytecode, YES_BOX, yesBoxAddress);
-    finalBytecode = replaceAll(finalBytecode, NO_BOX, noBoxAddress);
+    const { proposal } = this.props;
+    const { boothAddress, yesBoxAddress, noBoxAddress, id } = proposal;
+    console.log({ boothAddress, yesBoxAddress, noBoxAddress });
```
Comment (johba37) [inline src/volt/components/VoteControls/index.js:97]: no console.log in code

File: src/volt/components/VoteControls/index.js [hunk 2]
```diff
@@ -92,50 +92,19 @@ class VoteControls extends Component {
...
+    const motionId = proposal.id;
+    console.log({ motionId });
```
Comment (johba37) [inline src/volt/components/VoteControls/index.js:99]: no console.log in code

File: src/volt/components/VoteControls/index.js [hunk 3]
```diff
@@ -92,50 +92,19 @@ class VoteControls extends Component {
...
+
+    const params = generateProposal(motionId);
+    console.log({ params });
```
Comment (johba37) [inline src/volt/components/VoteControls/index.js:102]: no console.log in code

File: src/volt/components/VoteControls/index.js [hunk 4]
```diff
@@ -218,9 +187,9 @@ class VoteControls extends Component {
   }
 
   getDataFromTree() {
-    const { account, proposalId } = this.props;
-
-    console.log({proposalId});
+    const { account, proposal } = this.props;
+    const motionId = proposal.id;
+    console.log({ motionId });
```
Comment (johba37) [inline src/volt/components/VoteControls/index.js:192]: no console.log in code

**Review by johba37 — APPROVED** [review]
