### PR TITLE
Fix sorting in list view

### LINKED ISSUE #11: Main page UI
## Scope
Changing buner wallet UI into the new interface of the volt voting platform
- list view - ID + title + submitted votes on each proposal
- sorting function (ID number, number of votes, favorites)
- filter function (6 topics - Smart State / Economic Renaissance / Social Equality / Global Balance / Citizen Empowerment / EU Reform) 
- search function (title and number)

## Deliverables
- User Interface of mvp (https://xd.adobe.com/spec/2bc5e6f1-589f-4724-6275-73449bd3ddaa-5df4/)

- public deployment  to volt.deora.earth

## Roles
bounty gardener: @MaxKuck   / 5%
bounty worker: @MaxStalker   / 80%
bounty reviewer: name / 15%

### PR DESCRIPTION
**Pull request by MaxStalker**
Fixes #11 
It's not possible to sort by amount of votes.
Second param is changes to id and sorting method updated

### CODE REVIEW

File: src/MainPage.js [hunk 1]
```diff
@@ -22,8 +22,12 @@ export default function MainPage({
 }) {
   const filteredList = React.useMemo(() => {
     const sortFunctions = {
-      votes: (a, b) => 0,
-      name: (a, b) => a.title.localeCompare(b.title) * sortingOrder,
+      votes: (a, b) => {
+        const aVotes = userVotes[a.id] || 0;
```
Comment (johba37) [inline src/MainPage.js:26]: should use BN

**Review by johba37 — APPROVED** [review]
works, until there will be big numbers :)
